### PR TITLE
Feature/login flow v2

### PR DESCRIPTION
**Pull request by vauvenal5**
As discussed in #20 I cherry picked the networking changes and the login flow changes from @jld3103's branch. Once this is merged I will open a 2nd PR and change the `NextCloudClient` `host` parameter from `String` to `Uri`.

### CODE REVIEW

**Comment by provokateurin** [comment]
I think bumping the version to `2.0.0` makes more sense, because it's a breaking API change and users of `1.x.x` are expecting all versions to behave the same. https://dart.dev/tools/pub/versioning#semantic-versions says that the second slot is for breaking changes, but in this package it wasn't handled that way. What do you think?

**Comment by vauvenal5** [comment]
Yes, I agree. However, in this case maybe it is best to also add a commit for the Uri change on API level to not have to break API in the next PR again. It is just a small change, what do you think?

**Comment by provokateurin** [comment]
Yes

**Comment by vauvenal5** [comment]
What is the use case behind the client being able to handle a `host` param containing `index.php`?

**Comment by provokateurin** [comment]
I think it was just to sanitize the input and also there was a problem when you had the instance running under a path other than `/`, but I think you can safely remove that code.

**Comment by provokateurin** [comment]
Is it done?

**Comment by vauvenal5** [comment]
Yes.

**Comment by provokateurin** [comment]
Published

**Pull request merged**
