### PR TITLE
Fix webdav fileid

### LINKED ISSUE #46: LateInitializationError: Field 'fileId' has not been initialized
I want to be able to get the `fileId` of a `WebDavFile`.

I first loaded the files:
```Dart
//... 
var ncClient = NextCloudClient.withCredentials(Uri(host: baseUrl), "my@email.com", "myPassword");
//...
List<WebDavFile> allFiles = await ncClient.webDav.ls(path, props: WebDavProps.all);
```

Afterwards when I want to access the `fileId`:
```Dart
print(allFiles[index].fileId); //throws LateInit error

var res = await ncClient.webDav.getProps("/Documents/file.png", props: WebDavProps.all);
print(res.fileId); //throws LateInit error
```
And I get the following error: `LateInitializationError: Field 'fileId' has not been initialized`

Under the [Nextcloud WebDAV API for **Requesting Properties**](https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/basic.html#listing-folders-rfc4918) I saw that the `fileId` was defined as `<oc:fileid />`.
So I also tried to get the Property manually with `getOtherProp()` but I'm not quite sure if I used it correctly:
```Dart
print(allFiles[idx].getOtherProp('fileid', "http://owncloud.org/ns")); //returns null
print(allFiles[idx].getOtherProp('oc:fileid', "http://owncloud.org/ns")); //returns null
print(allFiles[idx].getOtherProp('fileid', "oc")); //returns null
```

I also looked at other properties. The following properties apart from `fileId` also threw a LateInit error:
`note, createdDate, uploadedDate`

Any help or fixing of the LateInit error would be appreciated.

### PR DESCRIPTION
**Pull request by provokateurin**
Fixes https://github.com/jld3103/dart-nextcloud/issues/46

### CODE REVIEW

**Comment by ElectrifyPowr** [comment]
I saw that you changed `fileId` to an optional variable to prevent the Null-Safety LateInit error.
Wouldn't it make sense to do that for the other `late` variables too, so that you can check on the client side if a value even exists?
Otherwise it is not easy to catch a LateInit error, whereas checking if a variable is null is easier.

**Comment by provokateurin** [comment]
Yes, but we should figure out which props are always present and which are optional to mark them accordingly

**Comment by ElectrifyPowr** [comment]
As I mentioned at the end of my [issue description](https://github.com/jld3103/dart-nextcloud/issues/46#issue-939584005), I found the following variables to cause the LateInit error:
`note`, `createdDate`, `uploadedDate` (in addition to the `fileId` of course)

**Comment by timosturm** [comment]
> Yes, but we should figure out which props are always present and which are optional to mark them accordingly

The `late` keyword should not be used like this anyway. See [effective dart](https://dart.dev/guides/language/effective-dart/usage#avoid-late-variables-if-you-need-to-check-whether-they-are-initialized).
The reason here is, that we can never be sure if any of the fields are initialized or not (the only exception seems to be `path` as it is part of the constructor).
The `late` keyword is appropriate for, e.g., lazy initialization but in the code we **have** to make sure they are initialized before being used. Here, this is not the case, for example when using the constructor: `WebDavFile('/myPath/')` non of the `late` fields are initialized.

Instead, all `late` fields should be converted to the respective `nullable` type. This allows the user to check if they are initialized: `webDavFile.fileId == null` or to specify a default value: `webDavFile.fileId ?? 42`.

**Comment by provokateurin** [comment]
Fixed in https://github.com/jld3103/nextcloud-harbour/blob/main/packages/nextcloud/lib/src/clients/custom/webdav/file.dart

**Pull request closed without merging**
